apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mongodb-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mongodb
                topologyKey: kubernetes.io/hostname
      {{- if and .Release.IsInstall }}
      initContainers:
        - name: chown-dir
          image: "rancher/mirrored-library-busybox:1.36.1"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args:
            - -c
            - |
              mkdir -p /home/yasin/bitnami/mongodb/data/
              [ "$(stat -c %u:%g /home/yasin/bitnami/mongodb/data/)" = "1001:1001" ] || chown -R 1001:1001 /home/yasin/bitnami/mongodb/data/ 2>/dev/null
          volumeMounts:
            - name: mongodb-data
              mountPath: /home/yasin/bitnami/
     {{- end }}
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/bash", "-c", "/opt/bitnami/scripts/mongodb/custom/startup.sh" ]
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONGODB_REPLICA_SET_NAME
              value: {{ .Values.mongodb.replicaSetName }}
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: "mongodb-0.mongodb-headless.$(MY_POD_NAMESPACE).svc.cluster.local"
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: "$(MY_POD_NAME).mongodb-headless.$(MY_POD_NAMESPACE).svc.cluster.local"
            - name: MONGODB_ROOT_USER
              value: {{ .Values.mongodb.rootUser }}
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-password
            - name: MONGODB_INITIAL_PRIMARY_ROOT_USER
              value: {{ .Values.mongodb.rootUser }}
            - name: MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-password
            - name: MONGODB_REPLICA_SET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: replica-set-key
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
            - name: mongodb-data
              mountPath: /bitnami/mongodb/data/
              subPath: mongodb/data/
            - name: startup
              mountPath: /opt/bitnami/scripts/mongodb/custom/startup.sh
              subPath: startup.sh
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: startup
          configMap:
            name: mongodb-script
            defaultMode: 0777
            items:
              - key: startup.sh
                path: startup.sh
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.mongodb.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.mongodb.storage }}