apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  root-password: {{ .Values.mongodb.rootPassword }}
  replica-set-key: {{ .Values.mongodb.replicaSetKey }}