image:
  pullPolicy: IfNotPresent
localPath: /home/yasin/data/jenkins/
busybox:
  repository: busybox
  tag: latest
jenkins:
  repository: yasin/jenkins
  tag: tls
  httpNodePort: 30000
hostAliases:
  - ip: 127.0.0.1
    hostnames:
      - docker.com.cn