# mongodb-replicaset.yaml
# kubectl exec -it -n yasin-app mongodb-0 -- mongo -uroot -pyasinwu --authenticationDatabase admin --eval 'rs.status()'
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: yasin-app
spec:
  serviceName: mongodb-headless
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mongodb
          image: bitnami/mongodb:5.0.5
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "/opt/bitnami/scripts/mongodb/custom/startup.sh" ]
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONGODB_REPLICA_SET_NAME
              value: "rs0"
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: "mongodb-0.mongodb-headless.$(MY_POD_NAMESPACE).svc.cluster.local"
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: "$(MY_POD_NAME).mongodb-headless.$(MY_POD_NAMESPACE).svc.cluster.local"
            - name: MONGODB_ROOT_USER
              value: "root"
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-password
            - name: MONGODB_INITIAL_PRIMARY_ROOT_USER
              value: "root"
            - name: MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-password
            - name: MONGODB_REPLICA_SET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: replica-set-key
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
            - name: mongodb-data
              mountPath: /bitnami/mongodb/data/
              subPath: mongodb/data/
            - name: startup
              mountPath: /opt/bitnami/scripts/mongodb/custom/startup.sh
              subPath: startup.sh
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: startup
          configMap:
            name: mongodb-script
            defaultMode: 0777
            items:
              - key: startup.sh
                path: startup.sh
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path-custom"
        resources:
          requests:
            storage: 8Gi