apiVersion: v1
kind: Service
metadata:
  name: dm
  namespace: dm
  labels:
    app: dm
spec:
  selector:
    app: dm
  ports:
    - name: tcp
      protocol: TCP
      port: 5236
      targetPort: 5236
      nodePort: 30236
  type: NodePort