apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: registry
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      {{- if .Values.registry.nodeName }}
      nodeName: {{ .Values.registry.nodeName }}
      {{- end }}
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /docker/registry/certs/server.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /docker/registry/certs/server.key
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /docker/registry/auth/htpasswd
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /docker/registry/data
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            - name: data
              mountPath: /docker/registry/data/
              subPath: registry/data/
            - name: certs
              mountPath: /docker/registry/certs/
            - name: auth
              mountPath: /docker/registry/auth/
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.storage.pvcName }}
        - name: certs
          configMap:
            name: registry-config
            items:
              - key: server.crt
                path: server.crt
              - key: server.key
                path: server.key
        - name: auth
          configMap:
            name: registry-config
            items:
              - key: htpasswd
                path: htpasswd